version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
